sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  alioss:
    endpoint: oss-eu-west-1.aliyuncs.com
    access-key-id: LTAI5tJT5T3g7EvSUwb28RxG
    access-key-secret: sYfyUScwEdFtOaob5xC2WRdG59BBZD
    bucket-name: skyyyl

  redis:
    host: localhost
    port: 6379
    database: 10